# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None

# /src is mounted as the project root in Docker
# Under Wine, we need Windows-style paths via Z: drive
project_root = 'Z:\\src'
frontend_dist = os.path.join(project_root, 'apps', 'desktop', 'dist')
entry_point = os.path.join(project_root, 'textforge', 'desktop_server.py')

a = Analysis(
    [entry_point],
    pathex=[project_root],
    binaries=[],
    datas=[
        (frontend_dist, 'frontend'),
    ],
    hiddenimports=[
        'textforge',
        'textforge.api',
        'textforge.config',
        'textforge.models',
        'textforge.pipeline',
        'textforge.desktop_server',
        'textforge.services',
        'textforge.services.rewrite',
        'textforge.services.chat',
        'textforge.providers',
        'textforge.providers.base',
        'textforge.providers.anthropic',
        'textforge.rewrite',
        'textforge.rewrite.engine',
        'textforge.rewrite.planner',
        'textforge.rewrite.prompts',
        'textforge.rewrite.protected_spans',
        'textforge.rewrite.transforms',
        'textforge.validation',
        'textforge.validation.semantic',
        'textforge.validation.claims',
        'textforge.validation.entities',
        'textforge.validation.numbers',
        'textforge.validation.quality',
        'textforge.provenance',
        'textforge.provenance.hashing',
        'textforge.provenance.models',
        'textforge.provenance.store',
        'textforge.watermark',
        'textforge.watermark.base',
        'textforge.watermark.benchmark',
        'textforge.watermark.metrics',
        'textforge.watermark.synthid_adapter',
        'uvicorn',
        'uvicorn.config',
        'uvicorn.main',
        'uvicorn.server',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.logging',
        'fastapi',
        'fastapi.staticfiles',
        'fastapi.responses',
        'starlette',
        'starlette.responses',
        'starlette.staticfiles',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'pydantic',
        'pydantic_settings',
        'httpx',
        'anthropic',
        'sqlalchemy',
        'sqlalchemy.ext.asyncio',
        'sqlalchemy.dialects.sqlite',
        'aiosqlite',
        'structlog',
        'yaml',
        'dotenv',
        'Levenshtein',
        'h11',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'sniffio',
        'httpcore',
        'certifi',
        'idna',
        'multipart',
        'multipart.multipart',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'numpy', 'scipy', 'PIL', 'IPython',
              'test', 'unittest', 'xmlrpc', 'pdb'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='TextForge',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    name='TextForge',
)
